### ISSUE TITLE
Assignment 2 & 3

### ISSUE THREAD

**Issue by EddAngulo** [jdposada/bioinf_202210#12]
Here we're creating the assigment2.Rmd & also modified a few lines into the .gitignore!

We added the following features to assigment2.Rmd:

- Load Eunomia Cohorts.
- Use Feature Extraction to generate per-person and aggregate covariates for a cohort of interest.
- Show the covariate data.
- Create SQLite Mimic IV demo database for optional task.

**Comment by EddAngulo** [comment]
Update Assignment 2 Markdown

**Comment by demarchenac** [comment]
I tried replicating the third section of the following instructions in order to train a Logistic Regression Model (LR) with PyTorch, but while training the model the following error is thrown:

![image](https://user-images.githubusercontent.com/20970325/160704066-49e52809-1859-41c6-baf1-5ceb46d1b0d1.png)

**Comment by jdposada** [comment]
It looks like it was running but when transfering the results there was an error. I saw [this ](https://github.com/rstudio/reticulate/issues/756) as an issue in the reticulate package, could you check if it works for you?

**Comment by demarchenac** [comment]
Hi @jdposada, I've tried following the issue you've mentioned ([rstudio issue #756](https://github.com/rstudio/reticulate/issues/756)). I tried running the following command: 
```r
devtools::install_github("rstudio/reticulate")
```

But it threw the following error:

> Error: .onLoad failed in loadNamespace() for 'pkgload', details:
>   call: loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]])
>   error: namespace ‘rlang’ 0.4.11 is already loaded, but >= 1.0.1 is required
> 

Thus I managed to update the rlang package via the following code:
```r
install.packages("rlang")
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://packagemanager.rstudio.com/all/__linux__/focal/latest/src/contrib/rlang_1.0.2.tar.gz'
Content type 'binary/octet-stream' length 1912199 bytes (1.8 MB)
==================================================
downloaded 1.8 MB

* installing *binary* package ‘rlang’ ...
* DONE (rlang)

The downloaded source packages are in
	‘/tmp/Rtmpwbo8Wi/downloaded_packages’
```

Then, I tried to install reticulate again: 
```r
devtools::install_github("rstudio/reticulate")
Downloading GitHub repo rstudio/reticulate@HEAD
...
* DONE (reticulate)
```

Then, I tried to run the sample code from the issue:
```r
library(reticulate)
library(Matrix)
N <- 6
set.seed(123)
sparse_mat <- sparseMatrix(
  i = sample(N, N, replace = F),
  j = sample(N, N, replace = F),
  x = runif(N),
  dims = c(N, N)
)
sparse_mat
sparse_mat_py <- r_to_py(sparse_mat)
```

But I still got the following error on  the line `sparse_mat_py <- r_to_py(sparse_mat)`:
> Error: Python shared library not found, Python bindings not loaded.
> Use reticulate::install_miniconda() if you'd like to install a Miniconda Python environment.
> 

In the end I couldn't solve the error at all, I don't know if maybe trying to use the `reticulate::install_miniconda()` would solve the error at all.

**Comment by camaranto** [comment]
I pushed a commit addressing this issue, the errors were solved we can proceed with the merge.

> I tried replicating the third section of the following instructions in order to train a Logistic Regression Model (LR) with PyTorch, but while training the model the following error is thrown:
> 
> ![image](https://user-images.githubusercontent.com/20970325/160704066-49e52809-1859-41c6-baf1-5ceb46d1b0d1.png)
